name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "requirements**.txt"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv pip install black pytest
        uv pip install -r requirements.txt
    - name: Check code style with Black
      run: |
        # Check if the code is formatted according to Black's standards
        black --check --line-length=100 --target-version=py311 .
    - name: Test with pytest
      run: |
        pytest
